#!/bin/bash

set -e

fix_dns() {
	SRC=$1
	DST=$2
	{
		echo "domain:             ${DST}"
		cat "data/dns/${SRC}" | grep '^nserver:' | tr -s " " | cut -d' ' -f2 | sort | uniq | xargs -i echo 'nserver:            {}'
		echo 'status:             CONNECT'
		echo 'mnt-by:             DN42-MNT'
		echo 'source:             DN42'
	} > "data/dns/${DST}"
}

fix_inetnum() {
	SRC=$1
	DST=$2
	CLASS=$3
	if [ -f "data/${CLASS}/${DST}" ]; then
		sed -r -i '/^(nserver|status|bgp-status|mnt-by|source|admin-c|tech-c):.*$/d' "data/${CLASS}/${DST}"
		{
			cat "data/dns/${SRC}" | grep '^nserver:' | tr -s " " | cut -d' ' -f2 | sort | uniq | xargs -i echo 'nserver:            {}'
			echo 'status:             ALLOCATED'
			echo 'bgp-status:         ignore'
			echo 'mnt-by:             DN42-MNT'
			echo 'source:             DN42'
		} >> "data/${CLASS}/${DST}"
	fi
}

fix_dns 'zone-servers.dn42' 'dn42'
fix_inetnum 'in-addr-servers.dn42' 'fd00::_8' 'inet6num'
fix_inetnum 'in-addr-servers.dn42' '10.0.0.0_8' 'inetnum'
for i in 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31; do
	fix_inetnum 'in-addr-servers.dn42' "172.${i}.0.0_16" 'inetnum'
done


